name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # atualizado para a versão mais nova

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3 python3-pip python3-setuptools python3-wheel libffi-dev libssl-dev libsqlite3-dev

      - name: Instalar Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Compilar APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4   # atualizado para a versão mais nova
        with:
          name: app-release
          path: bin/*.apk
